DATA:
  ROOT: C:\Users\patri\Documents\Python\Self_Driving_Car_Engineer\CarND-Traffic-Sign-Classifier-Project\traffic-signs-data
  REL_PATH: ""
  BATCH_SIZE: 512
  CLASS_NAMES: signnames.csv
MODEL:
  NUM_CLASSES: 43
  USE_BATCHN: True
  USE_DROPOUT: True
  DROPOUT: 0.25

OPTIM:
  LR: 0.001
  EPOCHS: 100
  WEIGHT_DECAY: 0.01

EXP:
  OUTPUT_PATH: ""
